### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by schae234** [csbio/CamocoHelixInstall#1]
Are you able to run the pytests?

When I do, I get:

```
(cobBox)schaefer@helix15:~/Codes/Camoco/tests$ py.test
/project/csbio/schaefer/.conda/cobBox/lib/python3.4/importlib/_bootstrap.py:321: UserWarning: Module argparse was already imported from /project/csbio/schaefer/.conda/cobBox/lib/python3.4/argparse.py, but /project/csbio/schaefer/local/lib/python3.4/site-packages is being added to sys.path
  return f(*args, **kwds)
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "/home/grad01/schaefer/.local/lib/python3.4/site-packages/_pytest/config.py", line 543, in importconftest
    mod = conftestpath.pyimport()
  File "/home/grad01/schaefer/.local/lib/python3.4/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/project/csbio/schaefer/Codes/Camoco/tests/conftest.py", line 6, in <module>
    from camoco.Config import cf
  File "/project/csbio/schaefer/Codes/Camoco/camoco/__init__.py", line 18, in <module>
    from .Camoco import Camoco
  File "/project/csbio/schaefer/Codes/Camoco/camoco/Camoco.py", line 7, in <module>
    from .Tools import log
  File "/project/csbio/schaefer/Codes/Camoco/camoco/Tools.py", line 17, in <module>
    import matplotlib.pylab as pylab
  File "/project/csbio/schaefer/.conda/cobBox/lib/python3.4/site-packages/matplotlib/pylab.py", line 231, in <module>
    import matplotlib.finance
  File "/project/csbio/schaefer/.conda/cobBox/lib/python3.4/site-packages/matplotlib/finance.py", line 36, in <module>
    from matplotlib.dates import date2num
  File "/project/csbio/schaefer/.conda/cobBox/lib/python3.4/site-packages/matplotlib/dates.py", line 137, in <module>
    import matplotlib.ticker as ticker
  File "/project/csbio/schaefer/.conda/cobBox/lib/python3.4/site-packages/matplotlib/ticker.py", line 158, in <module>
    from matplotlib import transforms as mtransforms
  File "/project/csbio/schaefer/.conda/cobBox/lib/python3.4/site-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: numpy.core.multiarray failed to import
ERROR: could not load /project/csbio/schaefer/Codes/Camoco/tests/conftest.py
```

Seems like an error with numpy...

**Comment by monprin** [comment]
Nooooooooo......... Well at least it's a different numpy error.

And yes I have at some point been able to run the tests. I will try again.

**Comment by schae234** [comment]
![](http://stream1.gifsoup.com/view6/4710118/emperor-evil-laugh-o.gif)
